### ISSUE TITLE
AttributeError: 'str' object has no attribute 'strftime'

### ISSUE THREAD

**Issue by adkist01** [exomut/evernote-dump#15]
I've debugged this stack trace and the problem is the sax parser is not required to give all characters at once. The parser splits the date string into 2 chunks for no logical reason, which breaks the date formatting.
See: [Stackoverflow - how to get results from xml sax parser in python](https://stackoverflow.com/questions/12263029/how-to-get-results-from-xml-sax-parser-in-python#12263340)

A solution is to change the interaction between `note_parser` and `note` to instead append characters to each note field, and then call `datetime.strptime` on the completed string in `get_created_date`.

```
Traceback (most recent call last):
  File "evernote_dump/evernote_dump.py", line 32, in <module>
    run_parse(settings)
  File "evernote-dump/evernote_dump/dump.py", line 27, in run_parse
    parser.parse(file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/Users/sysadmin/build/372final/Modules/pyexpat.c", line 471, in EndElement
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/expatreader.py", line 336, in end_element
    self._cont_handler.endElement(name)
  File "evernote-dump/evernote_dump/note_parser/note_parser.py", line 77, in endElement
    self.note.finalize()
  File "evernote-dump/evernote_dump/note_parser/note.py", line 178, in finalize
    self.create_markdown()
  File "evernote-dump/evernote_dump/note_parser/note.py", line 147, in create_markdown
    self.create_markdown_note_attr()
  File "evernote-dump/evernote_dump/note_parser/note.py", line 164, in create_markdown_note_attr
    self._markdown += "\n>Created Date: " + self._created_date.strftime(self.TIME_FORMAT) + "  "

```

**Comment by exomut** [comment]
Thank you for taking the time to report the issue.

The issues was on line 199 of note.py
[Changes](https://github.com/exomut/evernote-dump/commit/72a493329c8dc576352af5df3ec43f1964606449#diff-aa1acca08f5186657bc3b596e4465492)

A while back I added a try/except in-case a datetime could not be parsed on attachments. Since I didn't have any files that have an attachment date parse error, the exception was never caught during testing. In my exception catch, I set the date time to the current date, however I was using formatting to a string instead of a datetime.

Thanks again!

**Comment by adkist01** [comment]
The fix you gave still broke on other note fields. sax was still splitting fields into multiple chunks at random intervals. From what I've researched, this is a known behavior of Python sax. I made fixes on my own copy of the code to instead append characters in the note setter methods, and then do the type conversions in the getter methods. Doing that allowed your tool to work successfully on my archive of 11,000 notes. Thanks for making a great tool.

**Comment by exomut** [comment]
I found another location with the error and I think I solved the issue. However, like I said before, I don't have any files that cause the error.

If you get the time to test my fixed version let me know if it worked for you.

Thanks again for helping me out! Take care.
